spring:
  application:
    name: Food-Recycle

  data:
    mongodb:
      uri: mongodb+srv://foodrecycle:${MONGOPASSWORD}@cluster0.1ncrshs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: foodDatabase
