spring:
  application:
    name: Food-Recycle

  data:
    mongodb:
      uri: spring.data.mongodb.uri=mongodb+srv://${MONGOUSER}:${MONGOPASSWORD}@${MONGOHOST}/?retryWrites=true&w=majority&appName=Cluster0
      database: foodDatabase
